site_name: Thunderbird Council
site_url: https://council.thunderbird.net/
site_description: The Mozilla Thunderbird Council is the elected governing body for the Thunderbird Project.
site_author: The Thunderbird Council
nav:
  - Home: index.md
  - Members: members.md
  - Election: election.md
  - Decision making:
    - "Working Groups": decisions/working_groups.md
    - Motions: decisions/motions.md
  - Charter:
    - Bylaws: charter/bylaws.md
    - "Term sheet": charter/term_sheet.md

# Mkdocs is built with the mkdocs and readthedocs themes. Other themes
# are available. See https://www.mkdocs.org/user-guide/choosing-your-theme/
#
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/TB-Council-opt.svg
  font:
    text: Inter
  features:
    - navigation.sections

# We can use the 'mkdocs-video' plugin to embed a video, but that
# requires the video file to be hosted in this repository, which seems
# like a waste of storage space when we can just point people to youtube.
#
# If the 'mkdocs-video' plugin is used, then you need to 'pip install mkdocs-video'
#
#plugins:
#  - mkdocs-video

strict: true
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - ./stylesheets/extra.css

plugins:
  - privacy
  - search
